### PR TITLE
added a command to save daylist

### PR DESCRIPTION
**Pull request by PHAGUN-JAIN**
-> This PR addresses the issue for adding functionality of saving daylist spotify generated playlist

-> built the code locally and ran the binary to test the new command 

-> this cmd has been implemented with reference from save-weekly cmd implementation, so working is similar if some difference is needed can take up in further commits

### CODE REVIEW

**Comment by dvdmuckle** [comment]
This looks great! One request however, it looks like we have some variety of access to the full daylist name as it appears in Spotify. If I do `spc search daylist` I can see the full name of the daylist. Could the full name of the daylist be included in the resulting saved playlist?

**Comment by PHAGUN-JAIN** [comment]
> This looks great! One request however, it looks like we have some variety of access to the full daylist name as it appears in Spotify. If I do `spc search daylist` I can see the full name of the daylist. Could the full name of the daylist be included in the resulting saved playlist?

made changes addressing this 
image

**Comment by dvdmuckle** [comment]
One final change I just thought of after requesting the previous one :sweat_smile: , could we add the date in month/day/year format on the end, like in the Discover Weekly saver? I'm worried we might run into naming collisions for folks that listen to a lot of the same stuff at different times of day (such as myself :laughing: )

**Comment by PHAGUN-JAIN** [comment]
image

added the date function back as well i removed it in last commit since i thought name should be  exactly like what spotify gave  😆

**Comment by PHAGUN-JAIN** [comment]
hey @dvdmuckle did you get any time to look at this commenting in-case it skipped out of your schedule :)

**Comment by dvdmuckle** [comment]
Sorry, was a bit sick, looks good to me! I'll merge it.

**Pull request merged**
